<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('categories')->delete();

        \DB::table('categories')->insert(array(
            0 =>
            array(
                'id' => 1,
                'parent_id' => 0,
                'name_ar' => 'ناش أوتليت',
                'name_en' => 'NASH Outlet',
                'caption_ar' => 'ناش أوتليت',
                'caption_en' => 'NASH Outlet',
                'description_en' => 'NASH Outlet',
                'description_ar' => 'ناش أوتليت',
                'image' => '38.jpeg',
                'limited' => 1,
                'order' => 4,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:25',
                'updated_at' => '2019-04-01 18:52:52',
            ),
            1 =>
            array(
                'id' => 2,
                'parent_id' => 0,
                'name_ar' => 'ملابس أطفال',
                'name_en' => 'Kids Wear',
                'caption_ar' => 'ملابس أطفال',
                'caption_en' => 'Kids Wear',
                'description_en' => 'Kids Wear',
                'description_ar' => 'ملابس أطفال',
                'image' => '33.jpeg',
                'limited' => 0,
                'order' => 3,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:25',
                'updated_at' => '2019-04-01 18:45:25',
            ),
            2 =>
            array(
                'id' => 3,
                'parent_id' => 0,
                'name_ar' => 'قسم الرجال',
                'name_en' => 'Men',
                'caption_ar' => 'قسم الرجال',
                'caption_en' => 'Men',
                'description_en' => 'Men',
                'description_ar' => 'قسم الرجال',
                'image' => '32.jpeg',
                'limited' => 0,
                'order' => 2,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:25',
                'updated_at' => '2019-04-01 18:38:17',
            ),
            3 =>
            array(
                'id' => 4,
                'parent_id' => 0,
                'name_ar' => 'القسم النسائي',
                'name_en' => 'Women',
                'caption_ar' => 'نسائي',
                'caption_en' => 'Women',
                'description_en' => 'Dicta doloremque porro cum sit voluptatem. Et et vel ut est aut et.',
                'description_ar' => NULL,
                'image' => '1.jpeg',
                'limited' => 0,
                'order' => 1,
                'is_home' => 1,
                'is_featured' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:26',
                'updated_at' => '2019-03-19 16:06:58',
            ),

            10 =>
            array(
                'id' => 11,
                'parent_id' => 2,
                'name_ar' => 'أولاد',
                'name_en' => 'Boys',
                'caption_ar' => 'أولاد',
                'caption_en' => 'Boys',
                'description_en' => 'Boys',
                'description_ar' => 'أولاد',
                'image' => '6.jpeg',
                'limited' => 0,
                'order' => 1,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:26',
                'updated_at' => '2019-04-01 18:47:28',
            ),
            11 =>
            array(
                'id' => 12,
                'parent_id' => 2,
                'name_ar' => 'بنات',
                'name_en' => 'Girls',
                'caption_ar' => 'بنات',
                'caption_en' => 'Girls',
                'description_en' => 'Girls',
                'description_ar' => 'بنات',
                'image' => '5.jpeg',
                'limited' => 1,
                'order' => 2,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:26',
                'updated_at' => '2019-04-01 18:50:00',
            ),

            16 =>
            array(
                'id' => 17,
                'parent_id' => 3,
                'name_ar' => 'سديري - فيست',
                'name_en' => 'Men\'s Vest',
                'caption_ar' => 'سديري - فيست',
                'caption_en' => 'Men\'s Vest',
                'description_en' => 'Men\'s Vest',
                'description_ar' => 'سديري - فيست',
                'image' => '12.jpeg',
                'limited' => 0,
                'order' => 1,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:27',
                'updated_at' => '2019-04-01 18:40:12',
            ),
            17 =>
            array(
                'id' => 18,
                'parent_id' => 3,
                'name_ar' => 'كاجوال',
                'name_en' => 'Casual',
                'caption_ar' => 'كاجوال',
                'caption_en' => 'Casual',
                'description_en' => 'Casual',
                'description_ar' => 'كاجوال',
                'image' => '25.jpeg',
                'limited' => 1,
                'order' => 2,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:27',
                'updated_at' => '2019-04-01 18:42:01',
            ),

            22 =>
            array(
                'id' => 23,
                'parent_id' => 4,
                'name_ar' => 'كاجوال',
                'name_en' => 'Casual',
                'caption_ar' => 'مما شاهده حي بن يقظان في ذلك الموضع، وعلت الرمال.',
                'caption_en' => 'Dr. Nathanial Rosenbaum',
                'description_en' => 'Optio ut maiores nulla et eaque alias molestiae.',
                'description_ar' => 'على ذلك بالحيوان، علم أن الحكم على النبات أولى، إذ ليس للنبات من الادراكات و الأفعال قد تكون لها.',
                'image' => '34.jpeg',
                'limited' => 0,
                'order' => 1,
                'is_home' => 1,
                'is_featured' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:28',
                'updated_at' => '2019-03-19 16:11:07',
            ),
            23 =>
            array(
                'id' => 24,
                'parent_id' => 4,
                'name_ar' => 'بدلات إستقبال',
                'name_en' => 'House wear',
                'caption_ar' => 'بدلات إستقبال',
                'caption_en' => 'House wear',
                'description_en' => 'House wear',
                'description_ar' => 'بدلات إستقبال',
                'image' => '40.jpeg',
                'limited' => 0,
                'order' => 2,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-03-16 16:17:28',
                'updated_at' => '2019-04-01 18:27:56',
            ),

            28 =>
            array(
                'id' => 29,
                'parent_id' => 4,
                'name_ar' => 'بدلات خروج',
                'name_en' => 'Outdoor Wear',
                'caption_ar' => 'بدلات خروج',
                'caption_en' => 'Outdoor Wear',
                'description_en' => 'Outdoor Wear',
                'description_ar' => 'بدلات خروج',
                'image' => NULL,
                'limited' => 0,
                'order' => 3,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 18:31:09',
                'updated_at' => '2019-04-01 18:31:09',
            ),
            29 =>
            array(
                'id' => 30,
                'parent_id' => 4,
                'name_ar' => 'أحذية نسائي',
                'name_en' => 'Shoes',
                'caption_ar' => 'أحذية نسائي',
                'caption_en' => 'Shoes',
                'description_en' => 'Shoes',
                'description_ar' => 'أحذية نسائي',
                'image' => NULL,
                'limited' => 0,
                'order' => 4,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 18:32:25',
                'updated_at' => '2019-04-01 18:32:25',
            ),
            30 =>
            array(
                'id' => 31,
                'parent_id' => 4,
                'name_ar' => 'إكسسوارات',
                'name_en' => 'Accessories',
                'caption_ar' => 'إكسسوارات',
                'caption_en' => 'Accessories',
                'description_en' => 'Accessories',
                'description_ar' => 'إكسسوارات',
                'image' => NULL,
                'limited' => 0,
                'order' => 5,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 18:34:41',
                'updated_at' => '2019-04-01 18:34:41',
            ),
            31 =>
            array(
                'id' => 32,
                'parent_id' => 3,
                'name_ar' => 'أحذية وإكسسوارات',
                'name_en' => 'Shoes & Accessories',
                'caption_ar' => 'أحذية وإكسسوارات',
                'caption_en' => 'Shoes & Accessories',
                'description_en' => 'Shoes & Accessories',
                'description_ar' => 'أحذية وإكسسوارات',
                'image' => NULL,
                'limited' => 0,
                'order' => 4,
                'is_home' => 1,
                'is_featured' => 0,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 18:43:56',
                'updated_at' => '2019-04-01 18:43:56',
            ),
        ));
    }
}
